#!/usr/bin/env sh
set -eu

[ "$#" -ne 0 ] && { echo "No arguments expected" >&2; exit 1; }

if [ "$(id -u)" -eq 0 ]; then
    ASROOT=
elif command -v doas >/dev/null 2>&1; then
    ASROOT=doas
elif command -v sudo >/dev/null 2>&1; then
    ASROOT=sudo
else
    echo "Please install doas or sudo, or this script as root" >&2
    exit 1
fi

./extract_and_patch
cd hybrid-v35_64-nodebug-pcoem-6_30_223_271
make "-j$(nproc)"
$ASROOT make install
$ASROOT depmod -a
